workflows:
  ios-build:
    name: Solana iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    
    environment:
      groups:
        - telegram_credentials
      vars:
        BUNDLE_ID: "com.solana.messenger"
      xcode: latest
    
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    
    scripts:
      - name: Установка зависимостей
        script: |
          brew install python@3.11 bazelisk yasm
          export PATH="/opt/homebrew/opt/python@3.11/libexec/bin:$PATH"
          
      - name: Настройка Telegram API
        script: |
          mkdir -p build-input
          cat > build-input/build-configuration.json << EOF
          {
            "bundle_id": "com.solana.messenger",
            "api_id": "${TELEGRAM_API_ID}",
            "api_hash": "${TELEGRAM_API_HASH}",
            "team_id": "",
            "app_center_id": "",
            "is_internal_build": true,
            "is_appstore_build": false,
            "appstore_id": "",
            "app_specific_url_scheme": "solana"
          }
          EOF
          
      - name: Сборка iOS с Xcode подписью
        script: |
          # Используем автоматическую подпись Xcode
          python3 build-system/Make/Make.py \
            --cacheDir="$HOME/bazel-cache" \
            build \
            --configurationPath="build-input/build-configuration.json" \
            --buildNumber=1 \
            --configuration=release_arm64 \
            --xcodeManagedCodesigning

      - name: Создание IPA
        script: |
          mkdir -p output
          find . -name "*.app" -type d | head -1 | xargs -I {} cp -R {} output/
          cd output
          mkdir -p Payload
          mv *.app Payload/ 2>/dev/null || true
          zip -r Solana.ipa Payload
          cp Solana.ipa $CM_EXPORT_DIR/
          
    artifacts:
      - output/*.ipa
      - $CM_EXPORT_DIR/*.ipa
      
    publishing:
      scripts:
        - name: Готово
          script: |
            echo "✅ IPA файл готов!"
            echo "📱 Скачай и установи через AltStore"