workflows:
  ios-build:
    name: Solana iOS Build (Xcode Managed)
    instance_type: mac_mini_m2
    max_build_duration: 120
    
    environment:
      groups:
        - telegram_credentials
      vars:
        BUNDLE_ID: "com.solana.messenger"
      xcode: latest
    
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    
    scripts:
      - name: Установка зависимостей
        script: |
          brew install python@3.11 bazelisk yasm
          export PATH="/opt/homebrew/opt/python@3.11/libexec/bin:$PATH"
          
      - name: Настройка Telegram API
        script: |
          mkdir -p build-input
          cat > build-input/build-configuration.json << EOF
          {
            "bundle_id": "com.solana.messenger",
            "api_id": "${TELEGRAM_API_ID}",
            "api_hash": "${TELEGRAM_API_HASH}",
            "team_id": "",
            "app_center_id": "",
            "is_internal_build": true,
            "is_appstore_build": false,
            "appstore_id": "",
            "app_specific_url_scheme": "solana",
            "premium_iap_product_id": "org.solana.premium",
            "enable_siri": false,
            "enable_icloud": false,
            "google_client_scheme": "",
            "ng_env": "production"
          }
          EOF
          
      - name: Сборка для симулятора с Xcode Managed Codesigning
        script: |
          # Используем Xcode Managed Codesigning - НЕ требует профилей!
          python3 build-system/Make/Make.py \
            --cacheDir="$HOME/bazel-cache" \
            build \
            --configurationPath="build-input/build-configuration.json" \
            --xcodeManagedCodesigning \
            --buildNumber=1 \
            --configuration=release_sim_arm64

      - name: Установка ldid и создание IPA
        script: |
          brew install ldid
          mkdir -p output
          
          # Находим собранный .app
          APP_PATH=$(find bazel-bin -name "*.app" -type d | head -1)
          
          if [ -n "$APP_PATH" ]; then
            echo "✅ Найден .app: $APP_PATH"
            
            # Копируем приложение
            cp -R "$APP_PATH" output/Telegram.app
            
            # Создаём entitlements
            cat > output/entitlements.plist << 'ENTITLEMENTS'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>get-task-allow</key>
              <true/>
          </dict>
          </plist>
          ENTITLEMENTS
            
            # Подписываем через ldid
            echo "Подписываем через ldid..."
            ldid -Soutput/entitlements.plist output/Telegram.app/Telegram
            
            # Подписываем все фреймворки и расширения
            find output/Telegram.app -type f -perm +111 | while read binary; do
              if file "$binary" | grep -q "Mach-O"; then
                echo "Подписываем: $binary"
                ldid -S "$binary" 2>/dev/null || true
              fi
            done
            
            # Создаём IPA
            cd output
            mkdir -p Payload
            mv Telegram.app Payload/
            zip -r Solana-Messenger.ipa Payload
            cp Solana-Messenger.ipa $CM_EXPORT_DIR/
            
            echo "✅ IPA создан: Solana-Messenger.ipa"
            echo "📱 Установи через TrollStore или AltStore"
          else
            echo "❌ .app не найден"
            echo "Поиск артефактов..."
            find bazel-bin -name "*.app" -o -name "*.ipa" 2>/dev/null || echo "Ничего не найдено"
          fi
          
    artifacts:
      - output/*.ipa
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.txt
      
    publishing:
      scripts:
        - name: Готово
          script: |
            echo "✅ Сборка завершена!"
            echo "📱 IPA для симулятора создан"
            echo "⚠️ Для установки на реальное устройство нужно переподписать через AltStore"