workflows:
  ios-build:
    name: Solana iOS Build (Без подписи)
    instance_type: mac_mini_m2
    max_build_duration: 120
    
    environment:
      groups:
        - telegram_credentials
      vars:
        BUNDLE_ID: "com.solana.messenger"
      xcode: latest
    
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    
    scripts:
      - name: Установка зависимостей
        script: |
          brew install python@3.11 bazelisk yasm
          export PATH="/opt/homebrew/opt/python@3.11/libexec/bin:$PATH"
          
      - name: Настройка Telegram API
        script: |
          mkdir -p build-input
          cat > build-input/build-configuration.json << EOF
          {
            "bundle_id": "com.solana.messenger",
            "api_id": "${TELEGRAM_API_ID}",
            "api_hash": "${TELEGRAM_API_HASH}",
            "team_id": "FAKETEAM01",
            "app_center_id": "",
            "is_internal_build": true,
            "is_appstore_build": false,
            "appstore_id": "",
            "app_specific_url_scheme": "solana",
            "premium_iap_product_id": "org.solana.premium",
            "enable_siri": false,
            "enable_icloud": false,
            "google_client_scheme": "",
            "ng_env": "production"
          }
          EOF
          
      - name: Установка ldid (инструмент Saurik для подписи)
        script: |
          # Устанавливаем ldid - инструмент от создателя Cydia
          brew install ldid
          
      - name: Создание фейковых профилей и entitlements
        script: |
          mkdir -p fake-codesigning
          
          # Создаём entitlements для ad-hoc подписи
          cat > fake-codesigning/entitlements.plist << 'ENTITLEMENTS'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>application-identifier</key>
              <string>*</string>
              <key>get-task-allow</key>
              <true/>
          </dict>
          </plist>
          ENTITLEMENTS
          
          # Создаём фейковый provisioning profile
          cat > fake-codesigning/Solana.mobileprovision << 'PROFILE'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>AppIDName</key>
              <string>Solana Messenger</string>
              <key>Entitlements</key>
              <dict>
                  <key>aps-environment</key>
                  <string>development</string>
                  <key>application-identifier</key>
                  <string>FAKETEAM01.com.solana.messenger</string>
                  <key>get-task-allow</key>
                  <true/>
              </dict>
              <key>Name</key>
              <string>Solana Development</string>
              <key>TeamIdentifier</key>
              <array>
                  <string>FAKETEAM01</string>
              </array>
              <key>UUID</key>
              <string>00000000-0000-0000-0000-000000000001</string>
          </dict>
          </plist>
          PROFILE
          
      - name: Сборка для симулятора
        script: |
          python3 build-system/Make/Make.py \
            --cacheDir="$HOME/bazel-cache" \
            build \
            --configurationPath="build-input/build-configuration.json" \
            --codesigningInformationPath="fake-codesigning" \
            --buildNumber=1 \
            --configuration=release_sim_arm64

      - name: Создание IPA и подпись через ldid
        script: |
          mkdir -p output
          APP_PATH=$(find bazel-bin -name "*.app" -type d | head -1)
          
          if [ -n "$APP_PATH" ]; then
            echo "Найден .app: $APP_PATH"
            
            # Копируем приложение
            cp -R "$APP_PATH" output/Telegram.app
            
            # Подписываем через ldid (метод Saurik)
            echo "Подписываем через ldid..."
            ldid -Sfake-codesigning/entitlements.plist output/Telegram.app/Telegram
            
            # Подписываем все фреймворки
            find output/Telegram.app/Frameworks -name "*.framework" -type d | while read framework; do
              binary=$(basename "$framework" .framework)
              if [ -f "$framework/$binary" ]; then
                ldid -S "$framework/$binary"
              fi
            done
            
            # Создаём IPA
            cd output
            mkdir -p Payload
            mv Telegram.app Payload/
            zip -r Solana-ldid-signed.ipa Payload
            cp Solana-ldid-signed.ipa $CM_EXPORT_DIR/
            
            echo "✅ IPA создан с ldid подписью!"
            echo "📱 Этот IPA можно установить через AltStore"
          else
            echo "❌ .app не найден"
            find bazel-bin -name "*.app" -o -name "*.ipa" 2>/dev/null > $CM_EXPORT_DIR/search-results.txt
          fi
          
    artifacts:
      - output/*.ipa
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.txt
      
    publishing:
      scripts:
        - name: Готово
          script: |
            echo "✅ Сборка завершена!"
            echo "📱 IPA для симулятора создан"
            echo "⚠️ Для установки на реальное устройство нужно переподписать через AltStore"